const assert=require('node:assert/strict');
const {linearFit}=require('./www/statistics.js');
const close=(a,b)=>assert.ok(Math.abs(a-b)<1e-12,`${a} != ${b}`);
let f=linearFit([{x:1,y:5},{x:2,y:7},{x:3,y:9}]);
close(f.slope,2);close(f.intercept,3);close(f.r,1);
f=linearFit([{x:1,y:9},{x:2,y:7},{x:3,y:5}]);close(f.r,-1);
f=linearFit([{x:1,y:1},{x:2,y:0},{x:3,y:1}]);close(f.r,0);
assert.equal(linearFit([{x:1,y:1},{x:2,y:2}]),null);
assert.equal(linearFit([{x:1,y:1},{x:1,y:2},{x:1,y:3}]),null);
assert.equal(linearFit([{x:1,y:2},{x:2,y:2},{x:3,y:2}]),null);
assert.equal(linearFit([{x:1,y:2},{x:2,y:NaN},{x:3,y:4}]),null);
console.log('Linear-fit checks passed');
const {pearsonP}=require('./www/statistics.js');
close(pearsonP(.47,4),.53);
close(pearsonP(-.47,4),.53);
close(pearsonP(.5,3),2/3);
close(pearsonP(0,10),1);
close(pearsonP(1,10),0);
assert.equal(pearsonP(.5,2),null);
console.log('Pearson p-value checks passed');
